import 'bus_data.dart';
import 'bus_model.dart';

class StationData {

  static const List<String> stationList = [
    '300 Feet',
    'Abdulla',
    'Abdullahpur',
    'Adabor',
    'Adabor Shyamoli',
    'Adamjee College',
    'Adamjee School',
    'Agargaon',
    'Airport',
    'Amin Bazar',
    'Aminbazar',
    'Ansar Camp',
    'Arambagh',
    'Asad Gate',
    'Asad gate',
    'Ashulia',
    'Ashulia Bazar',
    'Azampur',
    'Azimpur',
    'Babubazar',
    'Badda',
    'Badda Link Road',
    'Baipayl',
    'Baitul Mukarram',
    'Bakshi Bazar',
    'Balughat',
    'Banani',
    'Banasree',
    'Bangla College',
    'Bangla Motor',
    'Bangladesh Bank',
    'Baromi',
    'Bashabo',
    'Bashtola',
    'Bashundhara',
    'Bashundhara (300 Feet Gate)',
    'Bata Signal',
    'Beribadh',
    'Beribadh Tin Rastar Moor',
    'Bijoy Sarani',
    'Bijoy Soroni',
    'Birulia',
    'Bishwa Road',
    'Board Bazar',
    'Bosila',
    'Bot tola',
    'CMH',
    'Cantonment',
    'Chairman Bari',
    'Chalantika Moor',
    'Chandra',
    'Chankhar Pul',
    'Chashara',
    'Chiriyakhana',
    'Chittagong Road',
    'City College',
    'College Gate',
    'Dainik Bangla Moor',
    'Darussalam',
    'Dayaganj',
    'Demra Staff Quarter',
    'Dhaka College',
    'Dhakeshwari',
    'Dhamra',
    'Dhamrai',
    'Dhanmondi 15',
    'Dhanmondi 27',
    'Dhanmondi 32',
    'Dholairpar',
    'Dhour',
    'Dhupkhola',
    'Dia Bari',
    'Diabari',
    'Duaripara',
    'ECB Square',
    'Eden College',
    'Elevated Expressway',
    'Fakirapul',
    'Fantasy Kingdom',
    'Farmgate',
    'Fulbaria',
    'GPO',
    'Gabtoli',
    'Gandaria',
    'Garrison (Cantonment)',
    'Gazipur',
    'Gazipur Bypass',
    'Gazipur Chourasta',
    'Ghatar Char',
    'Golap Shah Mazar',
    'Golapbag Chourasta',
    'Gulistan',
    'Gulshan 1',
    'Gulshan 2',
    'Gulshan Bridge',
    'Gulshan Link Road',
    'Hasnabad',
    'Hazaribag',
    'Hazipara',
    'Hemayetpur',
    'High Court',
    'House Building',
    'IDB',
    'Ittefaq Moor',
    'Jahangir Gate',
    'Jakir Hossen Road',
    'Jalkuri',
    'Jamgora',
    'Jamuna Future Park',
    'Janapath Moor',
    'Japan Garden City',
    'Jarun',
    'Jashimuddin',
    'Jashimuddin (Uttara)',
    'Jatrabari',
    'Jigatola',
    'Joydebpur',
    'Jurain',
    'Kachukhet',
    'Kadamtali',
    'Kakali',
    'Kakrail',
    'Kalabagan',
    'Kalabagan City College',
    'Kalampur',
    'Kallyanpur',
    'Kalshi',
    'Kamalapur',
    'Kamarpara',
    'Kamlapur',
    'Kamrangirchar',
    'Kanchan Bridge',
    'Kanchpur',
    'Karwan Bazar',
    'Kashimpur',
    'Katabon',
    'Kawlar',
    'Kawran Bazar',
    'Kazipara',
    'Kazla',
    'Keraniganj',
    'Khamar Bari',
    'Khamar Bari – Asad Gate – College Gate',
    'Khejur Bagan',
    'Khilgaon',
    'Khilgaon Flyover',
    'Khilgaon Khidma Hospital',
    'Khilkhet',
    'Kolabagan',
    'Konabari',
    'Kuchimura',
    'Kuril',
    'Kuril Bishwa Road',
    'Kuril Bissho Road',
    'Kuril Chourasta',
    'Kuril Flyover',
    'MES',
    'Madanpur',
    'Madhya Badda',
    'Malibagg Mor',
    'Malibagh',
    'Malibagh Moor',
    'Malibagh Rail Gate',
    'Malibagh Railgate',
    'Manik Mia Avenue',
    'Manik Nagar',
    'Manikganj',
    'Maowa',
    'Matsya Bhaban',
    'Matuail',
    'Mazar Road',
    'Meghna Ghat',
    'Merul',
    'Metro Hall',
    'Mill Gate',
    'Mirpur 1',
    'Mirpur 10',
    'Mirpur 11',
    'Mirpur 12',
    'Mirpur 13',
    'Mirpur 14',
    'Mirpur 14 Bus Stand',
    'Mirpur 2',
    'Mirpur 6',
    'Mirpur DOHS',
    'Mirpur Sony Cinema Hall',
    'Mitford Ghat',
    'Mogbazar',
    'Mohakhali',
    'Mohammadpur',
    'Mohammadpur Bus Stand',
    'Motijheel',
    'Motso Vobon',
    'Mouchak',
    'Mugdapara',
    'Nabisco',
    'Nadda',
    'Nandan Park',
    'Narshinghapur',
    'Natun Bazar',
    'Nawabganj',
    'Naya Bazar',
    'New Market',
    'Nila Market',
    'Nilkhet',
    'Nimtola',
    'Nobinagar',
    'Nobinagar Baipayl',
    'Nobinagar Chandra',
    'Notre Dame College',
    'Notun Bazar',
    'Old Airport',
    'Palashi',
    'Pallabi',
    'Palli Bidyut',
    'Paltan',
    'Panthapath',
    'Panthopoth',
    'Paturia',
    'Police Plaza',
    'Postagola',
    'Press Club',
    'Press Club Paltan',
    'Proshika Moor',
    'Purobi',
    'Rainkhola',
    'Rajarbag',
    'Rajendrapur',
    'Rajlakshmi',
    'Rajluxmi',
    'Rampura Bazar',
    'Rampura Bridge',
    'Ray Saheb Bazar',
    'Rayer Bazar',
    'Rayerbag',
    'Ring Road',
    'Ring road',
    'Rupnagar',
    'Rupnagar Abashik',
    'Sadarghat',
    'Sainik Club',
    'Salimullah Road',
    'Sanarpar',
    'Sat Rasta',
    'Satrasta',
    'Saudi Colony',
    'Savar',
    'Savar Cantonment',
    'Sayedabad',
    'Sayedabad Janapath Moor',
    'Science Lab',
    'Shahbag',
    'Shahjadpur',
    'Shanir Akhra',
    'Shankar',
    'Shantinagar',
    'Shewra',
    'Shewrapara',
    'Shia Masjid',
    'Shia Mosque',
    'Shib Bari',
    'Shibu Market',
    'Shimultola',
    'Shishu Mela',
    'Shiyal Bari',
    'Shonbari Sreenagar',
    'Shonir Akhra',
    'Showari Ghat',
    'Shukrabad',
    'Shukrabad Kalabagan',
    'Shyamoli',
    'Sign Board',
    'Signal',
    'Sikder Medical College',
    'Songsod Bhaban',
    'Sony Cenema Hall',
    'Sony Cinema Hall',
    'Sony Hall',
    'South Banasree',
    'Sreepur',
    'Staff Road',
    'Star Kabab',
    'Station Road',
    'Sura Bari',
    'TT Para',
    'Tajmahal Road',
    'Taltola',
    'Tarabo',
    'Technical',
    'Tejgaon College (Farmgate)',
    'Tikatuli',
    'Tolarbag',
    'Tongi',
    'Uttar Badda',
    'Uttara',
    'Uttara House Building',
    'Vashantek',
    'Victoria Park',
    'Vulta',
    'Wireless',
    'Workshop',
    'Zia Uddyan',
    'Zirabo',
    'Zirani Bazar',
  ];

  static Map<String, List<String>> stationMap = {
    'Gabtoli': [
      '7 No.',
      '8 No.',
      'Achim Paribahan',
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'Arnob',
      'BRTC',
      'BRTC Route 2',
      'BRTC Route 8',
      'Baishakhi',
      'Bashumoti',
      'Basumati',
      'BasumatiTransport',
      'BrihottorMirpur',
      'Cantonment Bus',
      'Champion',
      'D Link',
      'D One Transport',
      'First Ten',
      'Grameen',
      'Grameen Suveccha',
      'Itihash',
      'Jabale Noor Paribahan (2)',
      'Janjabil',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Moumita',
      'Nilachol',
      'One Transport',
      'Pallabi Super',
      'Prattay',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Ramjan',
      'Robrob',
      'Rupa Paribahan',
      'Rupkotha',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Super',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Thikana',
      'Thikana Express',
      'Titas',
      'Welcome'
    ],
    'Technical': [
      '7 No.',
      '8 No.',
      '9 No.',
      'Achim Paribahan',
      'Active Paribahan',
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'Arnob',
      'Ashirbad Paribahan',
      'BRTC',
      'BRTC Route 2',
      'Bahon',
      'Baishakhi',
      'Basumati',
      'Cantonment Bus',
      'Champion',
      'D Link',
      'D One Transport',
      'Dishari',
      'First Ten',
      'Grameen',
      'Grameen Suveccha',
      'Itihash',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Mirpur Metro',
      'Modhumita',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'One Transport',
      'Pallabi Local Service',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Ramjan',
      'Robrob',
      'Rupa Paribahan',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Ansar Camp': [
      '9 No.',
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Ashirbad Paribahan',
      'Bahon',
      'Cantonment Bus',
      'Champion',
      'Dishari',
      'First Ten',
      'Grameen',
      'Itihash',
      'Mirpur Metro',
      'Modhumita',
      'Nabakali',
      'New Vision',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Robrob',
      'Rupa Paribahan',
      'Somota Paribahan',
      'Talukdar',
      'Tanjil Paribahan',
      'Transilva'
    ],
    'Mirpur 1': [
      '9 No.',
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Al Makka',
      'Alif Route 1',
      'Alif Route 3',
      'Ashirbad Paribahan',
      'BRTC Route 8',
      'Bahon',
      'Bashumoti',
      'BasumatiTransport',
      'BikalpaBusAuto',
      'BrihottorMirpur',
      'Cantonment Bus',
      'Champion',
      'Dhaka Metro Service',
      'Dishari',
      'Everest Paribahan',
      'First Ten',
      'Grameen',
      'Itihash',
      'Jabale Noor Paribahan (2)',
      'Kanak',
      'Kironmala Paribahan',
      'Lams Paribahan',
      'Mirpur Metro',
      'Mirpur Mission',
      'Modhumita',
      'Mohona',
      'Nabakali',
      'New Vision',
      'Pallabi Local Service',
      'Pallabi Super',
      'Paristhan',
      'Power Paribahan',
      'Projapati',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Robrob',
      'Rupa Paribahan',
      'Rupkotha',
      'Sakalpa Transport',
      'Somota Paribahan',
      'Talukdar',
      'Tanjil Paribahan',
      'Titas',
      'Transilva'
    ],
    'Sony Cinema Hall': [
      '9 No.',
      'Achim Paribahan',
      'Akik',
      'Alif Route 1',
      'Ayat',
      'BRTC Route 8',
      'BasumatiTransport',
      'Cantonment Bus',
      'Champion',
      'Grameen',
      'Itihash',
      'Kanak',
      'Kironmala Paribahan',
      'Modhumita',
      'Mohona',
      'Nur E Makka',
      'Pallabi Local Service',
      'Pallabi Super',
      'Power Paribahan',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Rupa Paribahan',
      'Rupkotha',
      'Sakalpa Transport'
    ],
    'Mirpur 2': [
      '9 No.',
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Al Makka',
      'Alif Route 1',
      'Alif Route 3',
      'Ashirbad Paribahan',
      'Ayat',
      'BRTC Route 8',
      'Bahon',
      'BasumatiTransport',
      'Cantonment Bus',
      'Champion',
      'Everest Paribahan',
      'First Ten',
      'Grameen',
      'Itihash',
      'Kanak',
      'Modhumita',
      'Mohona',
      'Nur E Makka',
      'Pallabi Local Service',
      'Pallabi Super',
      'Paristhan',
      'Power Paribahan',
      'Projapati',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Robrob',
      'Rois',
      'Rupa Paribahan',
      'Rupkotha',
      'Sakalpa Transport'
    ],
    'Mirpur 10': [
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Al Makka',
      'Alif Route 1',
      'Alif Route 3',
      'Ayat',
      'BRTC Route 8',
      'Bahon',
      'Bashumoti',
      'BasumatiTransport',
      'BestTransport',
      'Bihanga',
      'BikalpaBusCitySuper',
      'Cantonment Bus',
      'Champion',
      'ETC',
      'ETC Transport',
      'Elite',
      'First Ten',
      'Grameen',
      'Hazi Transport',
      'Himachal',
      'Himachal Suveccha',
      'Itihash',
      'Jabale Noor Paribahan',
      'Jabale Noor Paribahan (2)',
      'Kanak',
      'Khajababa',
      'Mirpur Link',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Mohona',
      'Nishorgo',
      'Nur E Makka',
      'Pallabi Super',
      'Paristhan',
      'Power Paribahan',
      'Projapati',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Robrob',
      'Rois',
      'Runway Express',
      'Rupa Paribahan',
      'Rupkotha',
      'Safety Druti',
      'Sakalpa Transport',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia',
      'Trust Transport Services 1',
      'Trust Transport Services 2'
    ],
    'Mirpur 11': [
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'BRTC Route 8',
      'Bashumoti',
      'BasumatiTransport',
      'Bihanga',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC Transport',
      'Elite',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Kanak',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Link',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Nur E Makka',
      'Pallabi Local Service',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Rajdhani Super',
      'Runway Express',
      'Rupkotha',
      'Safety Druti',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Purobi': [
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Al Makka',
      'BRTC Route 8',
      'BasumatiTransport',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC Transport',
      'Elite',
      'Hazi Transport',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Kanak',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Link',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Nur E Makka',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Rajdhani Super',
      'Robrob',
      'Rupkotha',
      'Safety Druti',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Kalshi': [
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Al Makka',
      'BRTC Route 8',
      'Bashumoti',
      'BasumatiTransport',
      'Elite',
      'Jabale Noor Paribahan',
      'Jabale Noor Paribahan (2)',
      'Kanak',
      'Nur E Makka',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Rajdhani Super',
      'Robrob',
      'Rupkotha',
      'Tetulia',
      'Trust Transport Services (AC)',
      'Trust Transport Services 3'
    ],
    'ECB Square': [
      'Achim Paribahan',
      'Active Paribahan',
      'Akik',
      'Al Makka',
      'BRTC Route 8',
      'BasumatiTransport',
      'Kanak',
      'Mirpur Link',
      'Nur E Makka',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Rajdhani Super',
      'Robrob',
      'Runway Express',
      'Rupkotha',
      'Tetulia',
      'Trust Transport Services (AC)',
      'Trust Transport Services 3'
    ],
    'MES': [
      'Achim Paribahan',
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akik',
      'Alif Route 4',
      'Ashulia Classic',
      'BRTC Route 1',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Gazipur Paribahan',
      'Kanak',
      'Manjil Express',
      'Nur E Makka',
      'Omama International',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Provati Banasree',
      'Rajdhani Super',
      'Robrob',
      'Rupkotha',
      'Skyline',
      'Tetulia',
      'VIP 27'
    ],
    'Shewra': [
      'Achim Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akik',
      'Alif Route 4',
      'Ashulia Classic',
      'BRTC Route 1',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Gazipur Paribahan',
      'Kanak',
      'Manjil Express',
      'Nur E Makka',
      'Omama International',
      'Pallabi Super',
      'Paristhan',
      'Projapati',
      'Provati Banasree',
      'Rajdhani Super',
      'Rupkotha',
      'Shatabdi',
      'Skyline',
      'Tetulia',
      'VIP 27'
    ],
    'Kuril': ['Achim Paribahan'],
    'Bishwa Road': ['Achim Paribahan'],
    'Jamuna Future Park': [
      'Achim Paribahan',
      'Akash',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 6',
      'Desh Bangla',
      'Dewan',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Bashundhara': [
      'Achim Paribahan',
      'Akash',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 6',
      'Desh Bangla',
      'Dewan',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Nadda': [
      'Achim Paribahan',
      'Akash',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 6',
      'Desh Bangla',
      'Dewan',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Notun Bazar': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Achim Paribahan',
      'Agradut',
      'Akash',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 6',
      'Baishakhi',
      'Bihanga',
      'BondhuParibahan',
      'Desh Bangla',
      'Dewan',
      'Dhakar Chaka (Banani)',
      'Green Anabil',
      'Green Dhaka',
      'Gulshan Chaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan (2)',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Bashtola': [
      'Achim Paribahan',
      'Agradut',
      'Akash',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 6',
      'Baishakhi',
      'BondhuParibahan',
      'Desh Bangla',
      'Dewan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Shahjadpur': [
      'Achim Paribahan',
      'Agradut',
      'Akash',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 6',
      'BondhuParibahan',
      'Dewan',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Rajdhani Super',
      'Siam Transport',
      'Supravat',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Uttar Badda': [
      'Achim Paribahan',
      'Agradut',
      'Akik',
      'Anabil Super',
      'Asmani',
      'BRTC Route 3',
      'BRTC Route 4',
      'Baishakhi',
      'Desh Bangla',
      'Dewan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Salsabil',
      'Turag',
      'Winner'
    ],
    'Badda': [
      'Achim Paribahan',
      'Akash',
      'Anabil Super',
      'Asmani',
      'BRTC Route 6',
      'Bihanga',
      'BondhuParibahan',
      'Desh Bangla',
      'Dewan',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'Himachal',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Rois',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Madhya Badda': [
      'Achim Paribahan',
      'Alif Route 2',
      'Alif Route 3',
      'Arnob',
      'Asmani',
      'Falgun Art Transport Private Limited',
      'Nur E Makka',
      'Rajdhani Super'
    ],
    'Merul': [
      'Achim Paribahan',
      'Akash',
      'Alif Route 2',
      'Alif Route 3',
      'Anabil Super',
      'Arnob',
      'Asmani',
      'BRTC Route 6',
      'BondhuParibahan',
      'Desh Bangla',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Modhumita',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Robrob',
      'Salsabil',
      'Siam Transport',
      'Supravat',
      'Turag',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Rampura Bridge': [
      'Achim Paribahan',
      'Akash',
      'Alif Route 2',
      'Alif Route 3',
      'Anabil Super',
      'Arnob',
      'Asmani',
      'BRTC Route 6',
      'BondhuParibahan',
      'Desh Bangla',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'Himachal',
      'J M Super Paribahan',
      'Modhumita',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Rajdhani Super',
      'Ramjan',
      'Robrob',
      'Rois',
      'Salsabil',
      'Shadhin',
      'Siam Transport',
      'Supravat',
      'Taranga Plus',
      'Turag',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Banasree': [
      'Achim Paribahan',
      'Alif Route 2',
      'Alif Route 3',
      'Arnob',
      'Asmani',
      'Modhumita',
      'Rajdhani Super',
      'Ramjan',
      'Robrob',
      'Rois',
      'Shadhin',
      'Siam Transport',
      'Taranga Plus'
    ],
    'Demra Staff Quarter': [
      'Achim Paribahan',
      'Arnob',
      'Asmani',
      'Modhumita',
      'Rajdhani Super',
      'Ramjan',
      'Shadhin'
    ],
    'Shia Masjid': ['Active Paribahan'],
    'Adabor': [
      'Active Paribahan',
      'Alif Route 2',
      'Alif Route 4',
      'BhuiyanParibahan',
      'Rongdhonu Express'
    ],
    'Shyamoli': [
      '7 No.',
      '8 No.',
      '9 No.',
      'Active Paribahan',
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'Alif Route 2',
      'Alif Route 4',
      'Arnob',
      'Ashirbad Paribahan',
      'BRTC',
      'BRTC Route 2',
      'Bahon',
      'Baishakhi',
      'Basumati',
      'BhuiyanParibahan',
      'BikalpaBusCitySuper',
      'D Link',
      'D One Transport',
      'Dhaka Metro Service',
      'Dishari',
      'Grameen Suveccha',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Mirpur Metro',
      'Modhumita',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'Nishorgo',
      'One Transport',
      'Pallabi Local Service',
      'Paristhan',
      'Projapati',
      'Ramjan',
      'Rongdhonu Express',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Super',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Sony Hall': ['Active Paribahan'],
    'Shewrapara': [
      'Active Paribahan',
      'Alif Route 3',
      'Ayat',
      'BestTransport',
      'Bihanga',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC',
      'ETC Transport',
      'Elite',
      'Hazi Transport',
      'Himachal',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Link',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Nishorgo',
      'Rois',
      'Runway Express',
      'Safety Druti',
      'Sakalpa Transport',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Kuril Bishwa Road': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Akik',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 3',
      'BRTC Route 4',
      'BRTC Route 5',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Desh Bangla',
      'Dewan',
      'Elite',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Kanak',
      'Manjil Express',
      'Nur E Makka',
      'Omama International',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Raida',
      'Rajdhani Super',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Tetulia',
      'Turag',
      'VIP 27',
      'Victor Classic',
      'Victor Paribahan',
      'Winner'
    ],
    'Khilkhet': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'Bashumoti',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Desh Bangla',
      'Falgun Art Transport Private Limited',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Kanak',
      'Manjil Express',
      'Omama International',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Raida',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Turag',
      'VIP 27',
      'Victor Classic'
    ],
    'Airport': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Elevated Expressway',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'Bashumoti',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Desh Bangla',
      'Elite',
      'Falgun Art Transport Private Limited',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Kanak',
      'Manjil Express',
      'Omama International',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Raida',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Tetulia',
      'Turag',
      'VIP 27',
      'Victor Classic'
    ],
    'Jashimuddin': ['Active Paribahan'],
    'Rajlakshmi': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Desh Bangla',
      'Elite',
      'Falgun Art Transport Private Limited',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Kanak',
      'Manjil Express',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Raida',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Tetulia',
      'Turag',
      'VIP 27',
      'Victor Classic'
    ],
    'Azampur': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Desh Bangla',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Kanak',
      'Manjil Express',
      'Pallabi Super',
      'Prochesta',
      'Provati Banasree',
      'Raida',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Turag',
      'VIP 27',
      'Victor Classic'
    ],
    'House Building': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Desh Bangla',
      'Elite',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Kanak',
      'Manjil Express',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Raida',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Tetulia',
      'Turag',
      'VIP 27',
      'Victor Classic'
    ],
    'Abdullahpur': [
      'Active Paribahan',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Desh Bangla',
      'Elite',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Manjil Express',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Tetulia',
      'Turag',
      'VIP 27'
    ],
    'Savar': [
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'BRTC',
      'Baishakhi',
      'BrihottorMirpur',
      'Cantonment Bus',
      'D Link',
      'Grameen Suveccha',
      'Itihash',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Moumita',
      'Nilachol',
      'One Transport',
      'Purbachol Logistics and Transport',
      'Savar Paribahan',
      'Super',
      'Suvaccha',
      'Swajan',
      'Thikana',
      'Thikana Express',
      'Titas',
      'Welcome'
    ],
    'Hemayetpur': [
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'Arnob',
      'BRTC',
      'BRTC Route 2',
      'Baishakhi',
      'Cantonment Bus',
      'D Link',
      'Grameen Suveccha',
      'Itihash',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Moumita',
      'Nilachol',
      'One Transport',
      'Purbachol Logistics and Transport',
      'Rajdhani Super',
      'Savar Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Thikana',
      'Thikana Express',
      'Welcome'
    ],
    'Amin Bazar': [
      'Agradut',
      'Al Madina Plus One',
      'Arnob',
      'BRTC',
      'BRTC Route 2',
      'Baishakhi',
      'BrihottorMirpur',
      'Cantonment Bus',
      'D Link',
      'D One Transport',
      'Grameen Suveccha',
      'Itihash',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Moumita',
      'Nilachol',
      'One Transport',
      'Purbachol Logistics and Transport',
      'Savar Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Thikana',
      'Thikana Express',
      'Welcome'
    ],
    'Kallyanpur': [
      '7 No.',
      '8 No.',
      '9 No.',
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'Arnob',
      'Ashirbad Paribahan',
      'BRTC',
      'BRTC Route 2',
      'Bahon',
      'Baishakhi',
      'Basumati',
      'D Link',
      'D One Transport',
      'Dhaka Metro Service',
      'Dishari',
      'Grameen Suveccha',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Mirpur Metro',
      'Modhumita',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'One Transport',
      'Pallabi Local Service',
      'Paristhan',
      'Projapati',
      'Ramjan',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Shishu Mela': [
      '7 No.',
      '8 No.',
      '9 No.',
      'Agradut',
      'Ajmi',
      'Al Madina Plus One',
      'Alif Route 2',
      'Alif Route 4',
      'Arnob',
      'Ashirbad Paribahan',
      'BRTC',
      'BRTC Route 2',
      'Baishakhi',
      'Basumati',
      'BhuiyanParibahan',
      'BikalpaBusCitySuper',
      'D Link',
      'D One Transport',
      'Dishari',
      'Grameen Suveccha',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Mirpur Metro',
      'Modhumita',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'One Transport',
      'Pallabi Local Service',
      'Ramjan',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Tetulia',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Agargaon': [
      'Agradut',
      'Alif Route 2',
      'Alif Route 3',
      'Alif Route 4',
      'Arnob',
      'Ayat',
      'Baishakhi',
      'BestTransport',
      'BhuiyanParibahan',
      'Bihanga',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC',
      'ETC Transport',
      'Elite',
      'Hazi Transport',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Link',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Modhumita',
      'Nishorgo',
      'Rois',
      'Runway Express',
      'Safety Druti',
      'Sakalpa Transport',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Zia Uddyan': [
      'Agradut',
      'Alif Route 2',
      'Alif Route 4',
      'Arnob',
      'BhuiyanParibahan'
    ],
    'Bijoy Sarani': [
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      'Agradut',
      'Airport Bangabandhu Avenue',
      'Alif Route 2',
      'Alif Route 3',
      'Alif Route 4',
      'Arnob',
      'BRTC Articulated',
      'Baishakhi',
      'BhuiyanParibahan',
      'Bihanga',
      'BikalpaBusAuto',
      'Hazi Transport',
      'Himachal Suveccha',
      'Lams Paribahan',
      'Modhumita',
      'Sakalpa Transport',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran'
    ],
    'Jahangir Gate': [
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      'Agradut',
      'Airport Bangabandhu Avenue',
      'Alif Route 2',
      'Alif Route 3',
      'Alif Route 4',
      'Arnob',
      'BRTC Route 1',
      'BRTC Route 3',
      'BRTC Route 4',
      'Baishakhi',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bihanga',
      'Bikash',
      'BikashParibahan',
      'Dewan',
      'Modhumita',
      'Omama International',
      'Trust Transport Services (AC)',
      'Trust Transport Services 2',
      'Trust Transport Services 3'
    ],
    'Mohakhali': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Agradut',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Al Makka',
      'Alif Route 2',
      'Alif Route 3',
      'Alif Route 4',
      'Arnob',
      'Ashulia Classic',
      'BRTC Route 1',
      'BRTC Route 3',
      'BRTC Route 4',
      'Baishakhi',
      'Balaka',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bihanga',
      'Bikash',
      'BikashParibahan',
      'Cantonment Mini Service',
      'Dewan',
      'Gazipur Paribahan',
      'Himachal',
      'Himalay',
      'Manjil Express',
      'Modhumita',
      'Omama International',
      'Provati Banasree',
      'Rois',
      'Shatabdi',
      'Skyline',
      'Winner'
    ],
    'Wireless': [
      'Agradut',
      'Alif Route 2',
      'Alif Route 3',
      'Arnob',
      'BRTC Route 3',
      'BRTC Route 4',
      'Bihanga',
      'Dewan',
      'Modhumita',
      'Winner'
    ],
    'Gulshan 1': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Agradut',
      'Alif Route 2',
      'Alif Route 3',
      'Arnob',
      'BRTC Route 3',
      'BRTC Route 4',
      'Baishakhi',
      'Bihanga',
      'Dewan',
      'Dhakar Chaka',
      'Dip Paribahan',
      'Himachal',
      'Modhumita',
      'Robrob',
      'Rois',
      'Winner'
    ],
    'Badda Link Road': [
      'Agradut',
      'Alif Route 2',
      'Alif Route 3',
      'Arnob',
      'BRTC Route 3',
      'BRTC Route 4',
      'Baishakhi',
      'Dewan',
      'Modhumita',
      'Robrob',
      'Winner'
    ],
    'Fulbaria': [
      'Airport Bangabandhu Avenue',
      'D Link',
      'Grameen Suveccha',
      'Nabakali',
      'Provati Banasree',
      'Suvajatri'
    ],
    'Golap Shah Mazar': [
      '7 No.',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Basumati',
      'Dishari',
      'ETC',
      'ETC Transport',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Prochesta',
      'Provati Banasree',
      'Runway Express',
      'Savar Paribahan',
      'Shadhin Express',
      'Skyline',
      'Somoy Niyantran',
      'Supravat',
      'Suvajatri',
      'Swajan',
      'Tanjil Paribahan',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'GPO': [
      '6 No.',
      '6 No. Motijheel Banani',
      '7 No.',
      'ATCL',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Al Madina Plus One',
      'Al Makka',
      'BRTC',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 6',
      'BRTC Route 7',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'BondhuParibahan',
      'City Link',
      'Dishari',
      'ETC Transport',
      'FTCL',
      'Green Dhaka',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lal Sabuj (AC)',
      'MTCL-2',
      'Malancha',
      'Manjil Express',
      'Meghla Transport',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Moitri',
      'One Transport',
      'Prochesta',
      'Provati Banasree',
      'Raja City',
      'Rajanigandha',
      'Runway Express',
      'Savar Paribahan',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Skyline',
      'Somoy',
      'Somoy Niyantran',
      'Supravat',
      'Suvajatri',
      'Swajan',
      'Tanjil Paribahan',
      'Transilva',
      'Victor Classic',
      'Victor Paribahan',
      'Welcome'
    ],
    'Paltan': [
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      '7 No.',
      '8 No.',
      'ATCL',
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Al Madina Plus One',
      'Al Makka',
      'BRTC',
      'BRTC Articulated',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 6',
      'BRTC Route 7',
      'Bahon',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'BondhuParibahan',
      'City Link',
      'D One Transport',
      'Deepan',
      'Dipon',
      'Dishari',
      'ETC Transport',
      'FTCL',
      'FTCL (Alternate)',
      'Gazipur Paribahan',
      'Green Dhaka',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MTCL-2',
      'Malancha',
      'Manjil Express',
      'Meghla Transport',
      'Meshkat',
      'Midline',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Moitri',
      'New Vision',
      'Omama International',
      'One Transport',
      'Prochesta',
      'Provati Banasree',
      'Raja City',
      'Rajanigandha',
      'Runway Express',
      'Savar Paribahan',
      'Shadhin Express',
      'Shatabdi',
      'Shikhor Paribahan',
      'Skyline',
      'Somoy',
      'Somoy Niyantran',
      'Supravat',
      'Suvajatri',
      'Swajan',
      'Tanjil Paribahan',
      'Trust Transport Services 3',
      'Victor Classic',
      'Victor Paribahan',
      'Welcome'
    ],
    'Press Club': [
      '7 No.',
      '8 No.',
      'ATCL',
      'Airport Bangabandhu Avenue',
      'Al Madina Plus One',
      'BRTC',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 7',
      'Bahon',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'City Link',
      'D One Transport',
      'Dipon',
      'Dishari',
      'ETC Transport',
      'FTCL',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MTCL-2',
      'Malancha',
      'Meghla Transport',
      'Midline',
      'Mirpur Mission',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Moitri',
      'New Vision',
      'Omama International',
      'One Transport',
      'Raja City',
      'Rajanigandha',
      'Runway Express',
      'Savar Paribahan',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Suvajatri',
      'Swajan',
      'Tanjil Paribahan',
      'Trust Transport Services 3',
      'Welcome'
    ],
    'High Court': [
      '7 No.',
      '8 No.',
      'ATCL',
      'Airport Bangabandhu Avenue',
      'Al Madina Plus One',
      'BRTC',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 7',
      'Bahon',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'City Link',
      'D One Transport',
      'Dipon',
      'Dishari',
      'ETC Transport',
      'FTCL',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MTCL-2',
      'Malancha',
      'Meghla Transport',
      'Midline',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Moitri',
      'Nabakali',
      'New Vision',
      'Omama International',
      'One Transport',
      'Raja City',
      'Rajanigandha',
      'Runway Express',
      'Savar Paribahan',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Suvajatri',
      'Swajan',
      'Tanjil Paribahan',
      'Transilva',
      'Trust Transport Services 3',
      'Welcome'
    ],
    'Matsya Bhaban': [
      '8 No.',
      'ATCL',
      'Airport Bangabandhu Avenue',
      'BRTC',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 7',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'City Link',
      'D One Transport',
      'Deepan',
      'Dipon',
      'Dishari',
      'ETC Transport',
      'FTCL',
      'FTCL (Alternate)',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lams Paribahan',
      'MTCL-2',
      'Malancha',
      'Meghla Transport',
      'Meshkat',
      'Midline',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Moitri',
      'Omama International',
      'Ramjan',
      'Runway Express',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Suvajatri',
      'Taranga Plus',
      'Transilva'
    ],
    'Shahbag': [
      '4 No. Alike',
      '7 No.',
      '8 No.',
      'ATCL',
      'Airport Bangabandhu Avenue',
      'Al Madina Plus One',
      'BRTC',
      'BRTC Articulated',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 7',
      'Bahon',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'City Link',
      'D One Transport',
      'Deepan',
      'Dewan',
      'Dhaka Paribahan',
      'Dipon',
      'Dishari',
      'ETC',
      'ETC Transport',
      'FTCL',
      'FTCL (Alternate)',
      'Falgun Art Transport Private Limited',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MTCL-2',
      'Malancha',
      'Meghla Transport',
      'Meshkat',
      'Midline',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Moitri',
      'Nabakali',
      'New Vision',
      'Omama International',
      'One Transport',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Rongdhonu Express',
      'Runway Express',
      'Savar Paribahan',
      'Shadhin Express',
      'Shahria Enterprise',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Super',
      'Suvajatri',
      'Swajan',
      'Tanjil Paribahan',
      'Taranga Plus',
      'Transilva',
      'Trust Transport Services 2',
      'Trust Transport Services 3',
      'Welcome'
    ],
    'Bangla Motor': [
      '4 No. Alike',
      '8 No.',
      'Airport Bangabandhu Avenue',
      'Al Madina Plus One',
      'Ayat',
      'BRTC',
      'BRTC Articulated',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'D One Transport',
      'Dewan',
      'Dishari',
      'ETC',
      'ETC Transport',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Labbayek',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MM Lovely',
      'Meshkat',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'New Vision',
      'Omama International',
      'One Transport',
      'Runway Express',
      'Sakalpa Transport',
      'Shadhin',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Trust Transport Services 2',
      'Trust Transport Services 3',
      'Welcome'
    ],
    'Kawran Bazar': [
      '6 No.',
      '6 No. Motijheel Banani',
      '8 No.',
      'Airport Bangabandhu Avenue',
      'Al Madina Plus One',
      'Ayat',
      'BRTC',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'Basumati',
      'BestTransport',
      'BikalpaBusAuto',
      'D One Transport',
      'Dewan',
      'Dishari',
      'ETC Transport',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Labbayek',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MM Lovely',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'New Vision',
      'Omama International',
      'One Transport',
      'Runway Express',
      'Shadhin',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Trust Transport Services (AC)',
      'Trust Transport Services 2',
      'Trust Transport Services 3',
      'Welcome',
      'Winner'
    ],
    'Farmgate': [
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      '8 No.',
      'Airport Bangabandhu Avenue',
      'Al Madina Plus One',
      'Ayat',
      'BRTC',
      'BRTC Articulated',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 3',
      'BRTC Route 4',
      'Basumati',
      'BestSatabdiAC',
      'BestTransport',
      'BikalpaBusAuto',
      'Bikash',
      'BikashParibahan',
      'D One Transport',
      'Dewan',
      'Dhaka Paribahan',
      'Dishari',
      'ETC',
      'ETC Transport',
      'Everest Paribahan',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Labbayek',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MM Lovely',
      'Meshkat',
      'Mirpur Mission',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'New Vision',
      'Omama International',
      'One Transport',
      'Runway Express',
      'Sakalpa Transport',
      'Shadhin',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Super',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Trust Transport Services (AC)',
      'Trust Transport Services 2',
      'Trust Transport Services 3',
      'Welcome'
    ],
    'Chairman Bari': [
      'Airport Bangabandhu Avenue',
      'Al Makka',
      'Alif Route 4',
      'Ashulia Classic',
      'BRTC Route 1',
      'Balaka',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Gazipur Paribahan',
      'Manjil Express',
      'Omama International',
      'Provati Banasree',
      'Shatabdi',
      'Skyline'
    ],
    'Sainik Club': [
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Alif Route 4',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Cantonment Mini Service',
      'Gazipur Paribahan',
      'Omama International',
      'Skyline',
      'Trust Transport Services 1'
    ],
    'Banani': [
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Al Makka',
      'Alif Route 4',
      'Ashulia Classic',
      'BRTC Route 1',
      'Balaka',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Cantonment Mini Service',
      'Dhaka Paribahan',
      'Dhakar Chaka (Banani)',
      'Gazipur Paribahan',
      'Gulshan Chaka',
      'Manjil Express',
      'Omama International',
      'Provati Banasree',
      'Robrob',
      'Shatabdi',
      'Skyline',
      'Trust Transport Services 1',
      'VIP 27'
    ],
    'Kakali': [
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Al Makka',
      'Alif Route 4',
      'Ashulia Classic',
      'BRTC Route 1',
      'Balaka',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'Bikash',
      'BikashParibahan',
      'Cantonment Mini Service',
      'Gazipur Paribahan',
      'Manjil Express',
      'Omama International',
      'Provati Banasree',
      'Robrob',
      'Shatabdi',
      'Skyline',
      'VIP 27'
    ],
    'Staff Road': [
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Alif Route 4',
      'BRTC Route 1',
      'Balaka',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Gazipur Paribahan',
      'Manjil Express',
      'Omama International',
      'Provati Banasree',
      'Skyline'
    ],
    'Jashimuddin (Uttara)': [
      'Airport Bangabandhu Avenue',
      'Ajmeri Glory',
      'Akash',
      'Alif Route 4',
      'Anabil Super',
      'Ashulia Classic',
      'Asmani',
      'BRTC Route 1',
      'BRTC Route 6',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'BestSatabdiAC',
      'BhuiyanParibahan',
      'BikashParibahan',
      'Desh Bangla',
      'Elite',
      'Gazipur Paribahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Kanak',
      'Manjil Express',
      'Pallabi Super',
      'Paristhan',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Raida',
      'Rupkotha',
      'Salsabil',
      'Shatabdi',
      'Siam Transport',
      'Skyline',
      'Supravat',
      'Tetulia',
      'Turag',
      'VIP 27',
      'Victor Classic'
    ],
    'Sadarghat': [
      '7 No.',
      'Ajmeri Glory',
      'Mirpur United Service',
      'Savar Paribahan',
      'Skyline',
      'Supravat',
      'Swajan',
      'Tanjil Paribahan',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Ray Saheb Bazar': [
      '7 No.',
      'Ajmeri Glory',
      'Mirpur United Service',
      'Skyline',
      'Supravat',
      'Swajan',
      'Tanjil Paribahan',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Naya Bazar': [
      '7 No.',
      'Ajmeri Glory',
      'Akash',
      'Basumati',
      'Dishari',
      'Mirpur United Service',
      'Nabakali',
      'Prochesta',
      'Runway Express',
      'Shadhin Express',
      'Skyline',
      'Somoy Niyantran',
      'Swajan',
      'Tanjil Paribahan',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Kakrail': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Ajmeri Glory',
      'Akash',
      'Al Makka',
      'BRTC Route 6',
      'BondhuParibahan',
      'Falgun Art Transport Private Limited',
      'Gazipur Paribahan',
      'Green Dhaka',
      'Manjil Express',
      'Prochesta',
      'Provati Banasree',
      'Ramjan',
      'Rongdhonu Express',
      'Shahria Enterprise',
      'Shatabdi',
      'Skyline',
      'Supravat',
      'Taranga Plus',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Shantinagar': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Ajmeri Glory',
      'Akash',
      'Al Makka',
      'BRTC Route 6',
      'BondhuParibahan',
      'Falgun Art Transport Private Limited',
      'Gazipur Paribahan',
      'Green Dhaka',
      'Prochesta',
      'Provati Banasree',
      'Ramjan',
      'Skyline',
      'Supravat',
      'Taranga Plus',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Malibagh Moor': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Ajmeri Glory',
      'Akash',
      'Al Makka',
      'Ayat',
      'BRTC Route 6',
      'Balaka',
      'BondhuParibahan',
      'Gazipur Paribahan',
      'Green Dhaka',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Prochesta',
      'Provati Banasree',
      'Ramjan',
      'Sakalpa Transport',
      'Shatabdi',
      'Skyline',
      'Supravat',
      'Talukdar',
      'Taranga Plus',
      'Turag',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Mouchak': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Ajmeri Glory',
      'Akash',
      'Al Makka',
      'Ayat',
      'BRTC Route 6',
      'Balaka',
      'BondhuParibahan',
      'Falgun Art Transport Private Limited',
      'Gazipur Paribahan',
      'Green Dhaka',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Prochesta',
      'Ramjan',
      'Shadhin',
      'Shatabdi',
      'Skyline',
      'Supravat',
      'Talukdar',
      'Taranga Plus',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Nabisco': [
      'Ajmeri Glory',
      'Al Makka',
      'Ashulia Classic',
      'Balaka',
      'Dip Paribahan',
      'Gazipur Paribahan',
      'Manjil Express',
      'Provati Banasree',
      'Shatabdi',
      'Skyline',
      'Winner'
    ],
    'Tongi': [
      'Ajmeri Glory',
      'Akash',
      'Anabil Super',
      'BRTC Route 1',
      'BRTC Route 8',
      'Balaka',
      'Bashumoti',
      'BasumatiTransport',
      'Gazipur Paribahan',
      'Green Anabil',
      'Himalay',
      'J M Super Paribahan',
      'Provati Banasree',
      'Salsabil',
      'Skyline',
      'Supravat',
      'Turag',
      'VIP 27'
    ],
    'Station Road': [
      'Ajmeri Glory',
      'Anabil Super',
      'Balaka',
      'BasumatiTransport',
      'Gazipur Paribahan',
      'Green Anabil',
      'Provati Banasree',
      'Salsabil',
      'Skyline',
      'VIP 27'
    ],
    'Mill Gate': [
      'Ajmeri Glory',
      'Anabil Super',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'Gazipur Paribahan',
      'Green Anabil',
      'Provati Banasree',
      'Salsabil',
      'Skyline',
      'VIP 27'
    ],
    'Board Bazar': [
      'Ajmeri Glory',
      'Anabil Super',
      'BRTC Route 8',
      'Balaka',
      'BasumatiTransport',
      'Gazipur Paribahan',
      'Green Anabil',
      'Provati Banasree',
      'Salsabil',
      'Skyline',
      'VIP 27'
    ],
    'Gazipur Bypass': [
      'Ajmeri Glory',
      'Anabil Super',
      'BRTC Route 8',
      'Balaka',
      'Green Anabil',
      'Salsabil'
    ],
    'Konabari': [
      'Ajmeri Glory',
      'Alif Route 1',
      'Kironmala Paribahan',
      'Mohona',
      'Power Paribahan'
    ],
    'Chandra': [
      'Ajmeri Glory',
      'BRTC Route 2',
      'BrihottorMirpur',
      'Grameen Suveccha',
      'Itihash',
      'Moumita',
      'Purbachol Logistics and Transport',
      'Suvaccha',
      'Thikana',
      'Thikana Express'
    ],
    'Dhamrai': ['Ajmi', 'D One Transport'],
    'Aminbazar': ['Ajmi'],
    'College Gate': [
      '7 No.',
      '8 No.',
      '9 No.',
      'Ajmi',
      'Al Madina Plus One',
      'Ashirbad Paribahan',
      'BRTC',
      'Basumati',
      'BikalpaBusCitySuper',
      'D Link',
      'D One Transport',
      'Dishari',
      'Grameen Suveccha',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Mirpur Metro',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'One Transport',
      'Pallabi Local Service',
      'Paristhan',
      'Projapati',
      'Ramjan',
      'Rongdhonu Express',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Asad gate': ['Ajmi'],
    'Dhanmondi 27': [
      '7 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'Bahon',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'D Link',
      'Grameen Suveccha',
      'MTCL-2',
      'Mirpur Link',
      'Mirpur Metro',
      'Moumita',
      'Nabakali',
      'Nilachol',
      'Safety Druti',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Thikana',
      'Thikana Express',
      'Transilva'
    ],
    'Dhanmondi 32': [
      '7 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'Bahon',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'D Link',
      'Grameen Suveccha',
      'MTCL-2',
      'Mirpur Link',
      'Mirpur Metro',
      'Moumita',
      'Nabakali',
      'Nilachol',
      'Safety Druti',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Thikana',
      'Thikana Express',
      'Transilva'
    ],
    'Kalabagan': [
      '7 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'Bahon',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'D Link',
      'Grameen Suveccha',
      'MTCL-2',
      'Meghla Transport',
      'Mirpur Metro',
      'Moumita',
      'Nabakali',
      'Nilachol',
      'Rongdhonu Express',
      'Safety Druti',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'VIP 27',
      'Winner'
    ],
    'City College': [
      '13 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'BRTC Route 7',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'City Link',
      'D Link',
      'Deepan',
      'Dewan',
      'Dip Paribahan',
      'Dipon',
      'FTCL',
      'FTCL (Alternate)',
      'Grameen Suveccha',
      'Kamal Plus Paribahan',
      'MTCL-2',
      'Malancha',
      'Midline',
      'Mirpur Link',
      'Mirpur Metro',
      'Moitri',
      'Moumita',
      'Nilachol',
      'Raja City',
      'Ramjan',
      'Safety Druti',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Taranga Plus',
      'Thikana',
      'Thikana Express',
      'VIP 27',
      'Winner'
    ],
    'New Market': [
      '13 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'D Link',
      'Dewan',
      'Dhaka Metro Service',
      'Falgun Art Transport Private Limited',
      'Grameen Suveccha',
      'Kamal Plus Paribahan',
      'Mirpur Link',
      'Mirpur Metro',
      'Moumita',
      'Nilachol',
      'Nishorgo',
      'Safety Druti',
      'Somota Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'VIP 27',
      'Winner'
    ],
    'Nilkhet': [
      '13 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'D Link',
      'Dewan',
      'Dhaka Metro Service',
      'Falgun Art Transport Private Limited',
      'Grameen Suveccha',
      'Kamal Plus Paribahan',
      'Mirpur Link',
      'Mirpur Metro',
      'Moumita',
      'Nilachol',
      'Nishorgo',
      'Safety Druti',
      'Somota Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'VIP 27',
      'Winner'
    ],
    'Azimpur': [
      '13 No.',
      'Ajmi',
      'Ashirbad Paribahan',
      'BestSatabdiAC',
      'BikalpaBusCitySuper',
      'Bikash',
      'BikashParibahan',
      'D Link',
      'Dewan',
      'Dhaka Metro Service',
      'Dip Paribahan',
      'Falgun Art Transport Private Limited',
      'Grameen Suveccha',
      'Kamal Plus Paribahan',
      'Mirpur Link',
      'Mirpur Metro',
      'Moumita',
      'Nilachol',
      'Nishorgo',
      'Safety Druti',
      'Somota Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'VIP 27',
      'Winner'
    ],
    'Bakshi Bazar': [
      'Ajmi',
      'BikashParibahan',
      'D Link',
      'Grameen Suveccha',
      'Kamal Plus Paribahan',
      'Moumita',
      'Nilachol',
      'Somota Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express'
    ],
    'Gulistan': [
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      '7 No.',
      'ATCL',
      'Ajmi',
      'Al Madina Plus One',
      'Al Makka',
      'BRTC',
      'BRTC Articulated',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 6',
      'BRTC Route 7',
      'BestTransport',
      'BikalpaBusAuto',
      'BikashParibahan',
      'BondhuParibahan',
      'City Link',
      'Deepan',
      'Dhaka Paribahan',
      'Dipon',
      'Everest Paribahan',
      'FTCL',
      'FTCL (Alternate)',
      'Green Dhaka',
      'Hazi Transport',
      'Himachal Suveccha',
      'Kamal Plus Paribahan',
      'Khajababa',
      'Lal Sabuj (AC)',
      'MTCL-2',
      'Malancha',
      'Manjil Express',
      'Meghla Transport',
      'Midline',
      'Mirpur Transport Service',
      'Moitri',
      'Moumita',
      'Nilachol',
      'One Transport',
      'Raja City',
      'Rajanigandha',
      'Shikhor Paribahan',
      'Somota Paribahan',
      'Somoy',
      'Super',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Chittagong Road': [
      'Ajmi',
      'BRTC',
      'City Link',
      'FTCL',
      'Kamal Plus Paribahan',
      'Manjil Express',
      'Meshkat',
      'Nilachol',
      'Rajanigandha',
      'Somota Paribahan',
      'Suvaccha',
      'Talukdar'
    ],
    'Kadamtali': ['Akash', 'Runway Express', 'Shadhin Express'],
    'Keraniganj': [
      'Akash',
      'Basumati',
      'Dishari',
      'Everest Paribahan',
      'Nabakali',
      'Prochesta',
      'Runway Express',
      'Shadhin Express',
      'Somoy Niyantran'
    ],
    'Babubazar': [
      'Akash',
      'Basumati',
      'Dishari',
      'Janjabil',
      'Nabakali',
      'Prattay',
      'Prochesta',
      'Runway Express',
      'Shadhin Express',
      'Somoy Niyantran'
    ],
    'Malibagh Railgate': [
      'Akash',
      'Anabil Super',
      'BRTC Route 6',
      'BondhuParibahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Ramjan',
      'Salsabil',
      'Shadhin',
      'Supravat',
      'Taranga Plus',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Hazipara': [
      'Akash',
      'Anabil Super',
      'BRTC Route 6',
      'BondhuParibahan',
      'Green Anabil',
      'Green Dhaka',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Ramjan',
      'Shadhin',
      'Supravat',
      'Taranga Plus',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Rampura Bazar': [
      'Akash',
      'Anabil Super',
      'BRTC Route 6',
      'BondhuParibahan',
      'Desh Bangla',
      'Falgun Art Transport Private Limited',
      'Green Anabil',
      'Green Dhaka',
      'Himachal',
      'J M Super Paribahan',
      'Nur E Makka',
      'Prochesta',
      'Raida',
      'Ramjan',
      'Salsabil',
      'Shadhin',
      'Supravat',
      'Taranga Plus',
      'Turag',
      'Victor Classic',
      'Victor Paribahan'
    ],
    'Motijheel': [
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      '8 No.',
      'Al Madina Plus One',
      'Al Makka',
      'BRTC Articulated',
      'BRTC Route 1',
      'BRTC Route 2',
      'BRTC Route 4',
      'BRTC Route 6',
      'BRTC Route 7',
      'Bahon',
      'BestTransport',
      'BikalpaBusAuto',
      'D One Transport',
      'Deepan',
      'Dipon',
      'FTCL (Alternate)',
      'Gazipur Paribahan',
      'Green Dhaka',
      'Hazi Transport',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MTCL-2',
      'Meshkat',
      'Midline',
      'Mirpur Mission',
      'Moitri',
      'New Vision',
      'Omama International',
      'One Transport',
      'Rongdhonu Express',
      'Shahria Enterprise',
      'Shatabdi',
      'Transilva',
      'Trust Transport Services 3',
      'Welcome'
    ],
    'Mogbazar': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Al Makka',
      'Ayat',
      'Balaka',
      'Gazipur Paribahan',
      'Himalay',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Provati Banasree',
      'Sakalpa Transport',
      'Shadhin',
      'Shatabdi',
      'Talukdar'
    ],
    'Nandan Park': [
      'Al Madina Plus One',
      'Alif Route 1',
      'Grameen Suveccha',
      'Itihash',
      'Lal Sabuj (AC)',
      'Moumita',
      'One Transport',
      'Purbachol Logistics and Transport',
      'Savar Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'Welcome'
    ],
    'Zirani Bazar': [
      'Al Madina Plus One',
      'BRTC Route 2',
      'Grameen Suveccha',
      'Itihash',
      'Lal Sabuj (AC)',
      'Moumita',
      'One Transport',
      'Purbachol Logistics and Transport',
      'Savar Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'Welcome'
    ],
    'Baipayl': [
      'Al Madina Plus One',
      'Ashulia Classic',
      'BRTC Route 2',
      'Grameen Suveccha',
      'Lal Sabuj (AC)',
      'Moumita',
      'One Transport',
      'Purbachol Logistics and Transport',
      'Savar Paribahan',
      'Siam Transport',
      'Suvaccha',
      'Thikana',
      'Thikana Express',
      'Welcome'
    ],
    'Nobinagar': [
      'Al Madina Plus One',
      'Ashulia Classic',
      'BrihottorMirpur',
      'D One Transport',
      'Lal Sabuj (AC)',
      'Nilachol',
      'One Transport',
      'Siam Transport',
      'Super',
      'Suvaccha',
      'Welcome'
    ],
    'Asad Gate': [
      '7 No.',
      '8 No.',
      'ATCL',
      'Al Madina Plus One',
      'Ashirbad Paribahan',
      'BRTC',
      'BRTC Route 3',
      'Bahon',
      'Basumati',
      'BikalpaBusCitySuper',
      'D Link',
      'D One Transport',
      'Dhaka Metro Service',
      'Dishari',
      'Grameen Suveccha',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'MTCL-2',
      'Meshkat',
      'Mirpur Metro',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'Nishorgo',
      'One Transport',
      'Pallabi Local Service',
      'Paristhan',
      'Projapati',
      'Ramjan',
      'Rongdhonu Express',
      'Savar Paribahan',
      'Shadhin',
      'Shahria Enterprise',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Welcome'
    ],
    'Khamar Bari': [
      '8 No.',
      'Al Madina Plus One',
      'Ayat',
      'BRTC',
      'BRTC Route 3',
      'Basumati',
      'BestSatabdiAC',
      'BestTransport',
      'Bikash',
      'BikashParibahan',
      'Dishari',
      'ETC Transport',
      'Everest Paribahan',
      'Khajababa',
      'Labbayek',
      'Lal Sabuj (AC)',
      'MM Lovely',
      'Meshkat',
      'Mirpur Link',
      'Mirpur Mission',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'New Vision',
      'One Transport',
      'Safety Druti',
      'Shadhin',
      'Shadhin Express',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Welcome'
    ],
    'Kamalapur': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Al Madina Plus One',
      'Ayat',
      'BRTC Route 4',
      'Balaka',
      'Midline',
      'Sakalpa Transport'
    ],
    'Mirpur 14': [
      'Alif Route 1',
      'Bahon',
      'Cantonment Bus',
      'Cantonment Mini Service',
      'Champion',
      'First Ten',
      'Grameen',
      'Itihash',
      'Mohona',
      'Power Paribahan',
      'Purbachol Logistics and Transport',
      'Rupa Paribahan',
      'Trust Transport Services 1',
      'Trust Transport Services 2'
    ],
    'Mazar Road': ['Alif Route 1', 'Mohona', 'Power Paribahan'],
    'Rupnagar': [
      'Alif Route 1',
      'Kironmala Paribahan',
      'Mohona',
      'Power Paribahan'
    ],
    'Beribadh': ['Alif Route 1', 'Mohona', 'Power Paribahan', 'Siam Transport'],
    'Birulia': [
      'Alif Route 1',
      'Kironmala Paribahan',
      'Mohona',
      'Power Paribahan'
    ],
    'Ashulia': [
      'Alif Route 1',
      'Kironmala Paribahan',
      'Mohona',
      'Power Paribahan',
      'Siam Transport'
    ],
    'Zirabo': [
      'Alif Route 1',
      'Ashulia Classic',
      'Kironmala Paribahan',
      'Mohona',
      'Power Paribahan',
      'Siam Transport'
    ],
    'Fantasy Kingdom': [
      'Alif Route 1',
      'Ashulia Classic',
      'Mohona',
      'Siam Transport'
    ],
    'Shia Mosque': ['Alif Route 2', 'Rongdhonu Express', 'Tetulia'],
    'Japan Garden City': [
      'Alif Route 2',
      'Alif Route 4',
      'BhuiyanParibahan',
      'Tetulia'
    ],
    'Kazipara': [
      'Alif Route 3',
      'Ayat',
      'BestTransport',
      'Bihanga',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC',
      'ETC Transport',
      'Elite',
      'Hazi Transport',
      'Himachal',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Link',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Nishorgo',
      'Rois',
      'Runway Express',
      'Safety Druti',
      'Sakalpa Transport',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Ring Road': ['Alif Route 4', 'BhuiyanParibahan'],
    'Old Airport': ['Alif Route 4', 'BhuiyanParibahan'],
    'Sign Board': [
      'Anabil Super',
      'BRTC',
      'BikashParibahan',
      'City Link',
      'FTCL',
      'Green Anabil',
      'Himachal Suveccha',
      'Kamal Plus Paribahan',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Meghla Transport',
      'Meshkat',
      'Moumita',
      'Nilachol',
      'Rajanigandha',
      'Somota Paribahan',
      'Somoy',
      'Suvaccha',
      'Talukdar',
      'Thikana'
    ],
    'Shonir Akhra': [
      'Anabil Super',
      'BRTC',
      'BikashParibahan',
      'City Link',
      'FTCL',
      'Green Anabil',
      'Himachal Suveccha',
      'Kamal Plus Paribahan',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Meghla Transport',
      'Moumita',
      'Nilachol',
      'Rajanigandha',
      'Somota Paribahan',
      'Somoy',
      'Suvaccha',
      'Talukdar',
      'Thikana'
    ],
    'Jatrabari': [
      '8 No.',
      'Anabil Super',
      'BRTC',
      'BestTransport',
      'BikashParibahan',
      'City Link',
      'Desh Bangla',
      'FTCL',
      'Green Anabil',
      'Himachal Suveccha',
      'Himalay',
      'J M Super Paribahan',
      'Kamal Plus Paribahan',
      'Khajababa',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Meghla Transport',
      'Meshkat',
      'Moumita',
      'Nilachol',
      'Raida',
      'Rajanigandha',
      'Salsabil',
      'Shikhor Paribahan',
      'Somota Paribahan',
      'Somoy',
      'Suvaccha',
      'Talukdar',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Turag'
    ],
    'Sayedabad': [
      '8 No.',
      'Anabil Super',
      'BRTC',
      'Balaka',
      'BestTransport',
      'BikashParibahan',
      'City Link',
      'Desh Bangla',
      'FTCL',
      'Green Anabil',
      'J M Super Paribahan',
      'Kamal Plus Paribahan',
      'Khajababa',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Meghla Transport',
      'Meshkat',
      'Moumita',
      'Nilachol',
      'Raida',
      'Rajanigandha',
      'Salsabil',
      'Somota Paribahan',
      'Suvaccha',
      'Talukdar',
      'Thikana',
      'Thikana Express',
      'Transilva',
      'Turag'
    ],
    'Mugdapara': [
      'Anabil Super',
      'Bahon',
      'Desh Bangla',
      'Green Anabil',
      'J M Super Paribahan',
      'Labbayek',
      'MM Lovely',
      'Raida',
      'Salsabil',
      'Talukdar',
      'Turag'
    ],
    'Bashabo': [
      'Anabil Super',
      'Bahon',
      'Desh Bangla',
      'Green Anabil',
      'J M Super Paribahan',
      'Labbayek',
      'MM Lovely',
      'Midline',
      'Raida',
      'Salsabil',
      'Talukdar',
      'Turag'
    ],
    'Khilgaon': [
      'Anabil Super',
      'Bahon',
      'Desh Bangla',
      'Green Anabil',
      'J M Super Paribahan',
      'Midline',
      'Raida',
      'Salsabil',
      'Turag'
    ],
    'Gazipur Chourasta': [
      'Anabil Super',
      'BRTC Route 8',
      'Balaka',
      'Bashumoti',
      'BasumatiTransport',
      'Gazipur Paribahan',
      'Green Anabil',
      'Provati Banasree',
      'Salsabil',
      'Skyline',
      'VIP 27'
    ],
    'Duaripara': ['Ashirbad Paribahan'],
    'Rupnagar Abashik': ['Ashirbad Paribahan', 'Everest Paribahan'],
    'Shiyal Bari': ['Ashirbad Paribahan'],
    'Proshika Moor': ['9 No.', 'Ashirbad Paribahan'],
    'Shukrabad': [
      'ATCL',
      'Ashirbad Paribahan',
      'MTCL-2',
      'Nabakali',
      'Shahria Enterprise'
    ],
    'Jamgora': ['Ashulia Classic', 'Siam Transport'],
    'Ashulia Bazar': ['Ashulia Classic'],
    'Kamarpara': [
      'Ashulia Classic',
      'Bikash',
      'BikashParibahan',
      'Desh Bangla',
      'Pallabi Super',
      'Projapati',
      'Shatabdi',
      'Siam Transport'
    ],
    'Sat Rasta': ['Ashulia Classic'],
    'Dhour': ['Asmani', 'BikashParibahan', 'Siam Transport'],
    'Tarabo': ['Asmani'],
    'Madanpur': ['Asmani', 'BRTC', 'Himalay'],
    'Mohammadpur Bus Stand': ['ATCL', 'Taranga Plus'],
    'Kalabagan City College': ['ATCL'],
    'Science Lab': [
      '13 No.',
      '7 No.',
      'ATCL',
      'BRTC Route 7',
      'Bahon',
      'City Link',
      'Deepan',
      'Dewan',
      'Dhaka Metro Service',
      'Dipon',
      'FTCL',
      'FTCL (Alternate)',
      'Falgun Art Transport Private Limited',
      'Kamal Plus Paribahan',
      'MTCL-2',
      'Malancha',
      'Meghla Transport',
      'Midline',
      'Mirpur Metro',
      'Moitri',
      'Nabakali',
      'Nishorgo',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Rongdhonu Express',
      'Savar Paribahan',
      'Shahria Enterprise',
      'Suvajatri',
      'Taranga Plus',
      'Transilva',
      'Winner'
    ],
    'Katabon': [
      '7 No.',
      'ATCL',
      'Bahon',
      'Dewan',
      'Falgun Art Transport Private Limited',
      'Meghla Transport',
      'Nabakali',
      'Rongdhonu Express',
      'Shahria Enterprise'
    ],
    'Bata Signal': [
      'ATCL',
      'BRTC Route 7',
      'City Link',
      'Dipon',
      'FTCL',
      'Falgun Art Transport Private Limited',
      'MTCL-2',
      'Malancha',
      'Meghla Transport',
      'Midline',
      'Moitri',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Rongdhonu Express',
      'Suvajatri',
      'Taranga Plus',
      'Transilva'
    ],
    'Arambagh': [
      'ATCL',
      'Bahon',
      'Deepan',
      'Dipon',
      'FTCL (Alternate)',
      'MTCL-2',
      'Midline',
      'Moitri',
      'Shahria Enterprise'
    ],
    'Notre Dame College': ['ATCL'],
    'Chiriyakhana': [
      'Ayat',
      'BrihottorMirpur',
      'Dishari',
      'Kironmala Paribahan',
      'Mirpur Mission',
      'Modhumita',
      'Nabakali',
      'New Vision',
      'Nur E Makka',
      'Sakalpa Transport',
      'Somota Paribahan',
      'Talukdar',
      'Tanjil Paribahan',
      'Titas'
    ],
    'Taltola': [
      'Ayat',
      'BestTransport',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC Transport',
      'Elite',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Nishorgo',
      'Safety Druti',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Rajarbag': ['Ayat', 'Labbayek', 'MM Lovely', 'Talukdar'],
    'Bangla College': [
      '9 No.',
      'Bahon',
      'Mirpur Metro',
      'Paristhan',
      'Projapati'
    ],
    'Darussalam': [
      '9 No.',
      'Bahon',
      'D Link',
      'Grameen Suveccha',
      'Mirpur Metro',
      'Moumita',
      'Nilachol',
      'Paristhan',
      'Projapati',
      'Savar Paribahan',
      'Somota Paribahan',
      'Suvaccha',
      'Suvajatri',
      'Thikana',
      'Thikana Express'
    ],
    'Dainik Bangla Moor': [
      '8 No.',
      'Bahon',
      'D One Transport',
      'Lams Paribahan',
      'Meshkat',
      'New Vision',
      'Omama International',
      'Trust Transport Services 3'
    ],
    'Kamlapur': ['Bahon'],
    'Manik Nagar': ['Balaka', 'Labbayek', 'MM Lovely', 'Talukdar'],
    'TT Para': ['Balaka'],
    'Satrasta': ['Balaka', 'Manjil Express', 'Provati Banasree', 'Shatabdi'],
    'Manik Mia Avenue': ['Basumati'],
    'Maowa': ['Basumati', 'Prochesta', 'Shadhin Express'],
    'Diabari': ['BestSatabdiAC', 'Victor Classic'],
    'Ittefaq Moor': ['BestTransport', 'Meshkat', 'Shahria Enterprise'],
    'Mirpur 12': [
      '9 No.',
      'Bihanga',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC',
      'ETC Transport',
      'Hazi Transport',
      'Himachal Suveccha',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Pallabi Local Service',
      'Runway Express',
      'Safety Druti',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran'
    ],
    'Gulshan Bridge': ['Bihanga'],
    'Pallabi': [
      '9 No.',
      'Bashumoti',
      'BikalpaBusAuto',
      'BikalpaBusCitySuper',
      'ETC',
      'ETC Transport',
      'Elite',
      'Hazi Transport',
      'Himachal Suveccha',
      'Jabale Noor Paribahan',
      'Khajababa',
      'Lams Paribahan',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Safety Druti',
      'Shadhin Express',
      'Shikhor Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Tetulia'
    ],
    'Dhakeshwari': [
      'BikalpaBusCitySuper',
      'Somota Paribahan',
      'Suvaccha',
      'Thikana'
    ],
    'Matuail': [
      'BRTC',
      'BikashParibahan',
      'City Link',
      'FTCL',
      'Green Anabil',
      'Himachal Suveccha',
      'Kamal Plus Paribahan',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Meshkat',
      'Moumita',
      'Nilachol',
      'Rajanigandha',
      'Somota Paribahan',
      'Somoy',
      'Suvaccha',
      'Talukdar',
      'Thikana'
    ],
    'Rayerbag': [
      'BRTC',
      'BikashParibahan',
      'City Link',
      'FTCL',
      'Green Anabil',
      'Himachal Suveccha',
      'Kamal Plus Paribahan',
      'Labbayek',
      'MM Lovely',
      'Manjil Express',
      'Meshkat',
      'Moumita',
      'Nilachol',
      'Rajanigandha',
      'Somota Paribahan',
      'Somoy',
      'Suvaccha',
      'Talukdar',
      'Thikana'
    ],
    'Chankhar Pul': [
      'BikashParibahan',
      'D Link',
      'Grameen Suveccha',
      'Kamal Plus Paribahan',
      'Moumita',
      'Nilachol',
      'Somota Paribahan',
      'Suvaccha',
      'Thikana',
      'Thikana Express'
    ],
    'Palashi': ['Borak'],
    'Meghna Ghat': ['Borak'],
    'Kanchpur': ['BRTC', 'Meghla Transport'],
    'Rajluxmi': ['BRTC Elevated Expressway'],
    'Kawlar': ['BRTC Elevated Expressway'],
    'Elevated Expressway': ['BRTC Elevated Expressway'],
    'Tejgaon College (Farmgate)': ['BRTC Elevated Expressway'],
    'Khejur Bagan': ['BRTC Elevated Expressway'],
    'Songsod Bhaban': ['BRTC Elevated Expressway'],
    'Bijoy Soroni': ['BRTC Elevated Expressway'],
    'Khamar Bari – Asad Gate – College Gate': ['BRTC Route 2'],
    'Mohammadpur': [
      '13 No.',
      'BRTC Route 3',
      'BRTC Route 7',
      'City Link',
      'FTCL',
      'FTCL (Alternate)',
      'Kamal Plus Paribahan',
      'MTCL-2',
      'Malancha',
      'Meshkat',
      'Midline',
      'Moitri',
      'Nishorgo',
      'Paristhan',
      'Projapati',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Rongdhonu Express',
      'Shadhin'
    ],
    'Vulta': ['BRTC Route 5', 'Meghla Transport'],
    'Kanchan Bridge': ['BRTC Route 5'],
    'Nila Market': ['BRTC Route 5'],
    '300 Feet': ['BRTC Route 5'],
    'Bashundhara (300 Feet Gate)': ['BRTC Route 5'],
    'Shankar': [
      '13 No.',
      'BRTC Route 7',
      'City Link',
      'Deepan',
      'Dipon',
      'FTCL',
      'FTCL (Alternate)',
      'Kamal Plus Paribahan',
      'Malancha',
      'Midline',
      'Moitri',
      'Nishorgo',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Taranga Plus'
    ],
    'Star Kabab': [
      '13 No.',
      'BRTC Route 7',
      'City Link',
      'Dipon',
      'FTCL',
      'Kamal Plus Paribahan',
      'Malancha',
      'Midline',
      'Moitri',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Taranga Plus'
    ],
    'Dhanmondi 15': [
      '13 No.',
      'BRTC Route 7',
      'City Link',
      'Deepan',
      'Dipon',
      'FTCL (Alternate)',
      'Kamal Plus Paribahan',
      'Malancha',
      'Midline',
      'Moitri',
      'Nishorgo',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Taranga Plus'
    ],
    'Jigatola': [
      '13 No.',
      'BRTC Route 7',
      'City Link',
      'Deepan',
      'Dipon',
      'FTCL',
      'FTCL (Alternate)',
      'Kamal Plus Paribahan',
      'Malancha',
      'Midline',
      'Moitri',
      'Nishorgo',
      'Raja City',
      'Rajanigandha',
      'Ramjan',
      'Taranga Plus'
    ],
    'Balughat': ['4 No. Alike', 'BRTC Articulated'],
    'Cantonment': ['BRTC Articulated'],
    'Kachukhet': [
      'Cantonment Mini Service',
      'Trust Transport Services 1',
      'Trust Transport Services 2'
    ],
    'Vashantek': [
      'Champion',
      'First Ten',
      'Purbachol Logistics and Transport',
      'Rupa Paribahan'
    ],
    'Bosila': ['City Link', 'Paristhan', 'Projapati', 'Raja City', 'Shadhin'],
    'Ghatar Char': ['City Link', 'Kamal Plus Paribahan', 'Raja City'],
    'Dhamra': ['D Link'],
    'Kalampur': ['D One Transport'],
    'Tajmahal Road': ['Deepan', 'Dipon'],
    'Postagola': [
      'Desh Bangla',
      'Raida',
      'Raja City',
      'Rongdhonu Express',
      'Salsabil',
      'Shahria Enterprise',
      'Thikana Express'
    ],
    'Dholairpar': ['Desh Bangla', 'Raida', 'Salsabil', 'Thikana Express'],
    'Malibagh': ['Desh Bangla'],
    'Kuril Chourasta': ['Desh Bangla', 'Raida', 'Salsabil', 'Turag'],
    'Eden College': ['Dewan', 'Nishorgo', 'Winner'],
    'Police Plaza': ['Dhakar Chaka'],
    'Gulshan 2': [
      '6 No.',
      '6 No. Motijheel Banani',
      'Dhakar Chaka',
      'Dhakar Chaka (Banani)',
      'Gulshan Chaka',
      'Robrob'
    ],
    'Shukrabad Kalabagan': ['Dhaka Metro Service'],
    'Uttara': ['Dhaka Paribahan'],
    'Gazipur': ['Dhaka Paribahan'],
    'Shib Bari': ['Dhaka Paribahan', 'Gazipur Paribahan'],
    'Salimullah Road': ['Dipon'],
    'Jakir Hossen Road': ['Dipon'],
    'Baitul Mukarram': ['Dipon'],
    'Kolabagan': ['Dip Paribahan'],
    'Panthopoth': ['Dip Paribahan'],
    'Karwan Bazar': ['Dip Paribahan'],
    'Gulshan Link Road': ['Dip Paribahan'],
    'Kuril Bissho Road': [
      'Dip Paribahan',
      'Falgun Art Transport Private Limited'
    ],
    'Motso Vobon': ['Falgun Art Transport Private Limited'],
    'Malibagg Mor': ['Falgun Art Transport Private Limited'],
    'Malibagh Rail Gate': ['Falgun Art Transport Private Limited'],
    'Natun Bazar': ['Falgun Art Transport Private Limited'],
    'Uttara House Building': ['Falgun Art Transport Private Limited'],
    'Sony Cenema Hall': ['First Ten'],
    'Janapath Moor': [
      '8 No.',
      'FTCL',
      'Himachal Suveccha',
      'Labbayek',
      'MM Lovely',
      'Raida',
      'Shikhor Paribahan',
      'Talukdar',
      'Transilva'
    ],
    'Chashara': ['Green Anabil', 'Himachal Suveccha', 'Moumita'],
    'Shibu Market': ['Green Anabil', 'Himachal Suveccha', 'Moumita'],
    'Jalkuri': ['Green Anabil', 'Himachal Suveccha', 'Moumita'],
    '': [
      '13 No.',
      '4 No. Alike',
      '6 No.',
      '6 No. Motijheel Banani',
      '7 No.',
      '8 No.',
      '9 No.',
      'Hazi Transport',
      'Himachal',
      'Himachal Suveccha',
      'Himalay',
      'Itihash',
      'J M Super Paribahan',
      'Jabale Noor Paribahan',
      'Jabale Noor Paribahan (2)',
      'Janjabil',
      'Kamal Plus Paribahan',
      'Kanak',
      'Khajababa',
      'Kironmala Paribahan',
      'Labbayek',
      'Lal Sabuj (AC)',
      'Lams Paribahan',
      'MM Lovely',
      'MTCL-2',
      'Malancha',
      'Manjil Express',
      'Meghla Transport',
      'Meshkat',
      'Midline',
      'Mirpur Link',
      'Mirpur Metro',
      'Mirpur Mission',
      'Mirpur Transport Service',
      'Mirpur United Service',
      'Modhumita',
      'Mohona',
      'Moitri',
      'Moumita',
      'Nabakali',
      'New Vision',
      'Nilachol',
      'Nishorgo',
      'Nur E Makka',
      'Omama International',
      'One Transport',
      'Pallabi Local Service',
      'Pallabi Super',
      'Paristhan',
      'Power Paribahan',
      'Prattay',
      'Prochesta',
      'Projapati',
      'Provati Banasree',
      'Purbachol Logistics and Transport',
      'Raida',
      'Raja City',
      'Rajanigandha',
      'Rajdhani Super',
      'Ramjan',
      'Robrob',
      'Rois',
      'Rongdhonu Express',
      'Runway Express',
      'Rupa Paribahan',
      'Rupkotha',
      'Safety Druti',
      'Sakalpa Transport',
      'Salsabil',
      'Savar Paribahan',
      'Shadhin',
      'Shadhin Express',
      'Shahria Enterprise',
      'Shatabdi',
      'Shikhor Paribahan',
      'Siam Transport',
      'Skyline',
      'Somota Paribahan',
      'Somoy',
      'Somoy Niyantran',
      'Super',
      'Supravat',
      'Suvaccha',
      'Suvajatri',
      'Swajan',
      'Talukdar',
      'Tanjil Paribahan',
      'Taranga Plus',
      'Tetulia',
      'Thikana',
      'Thikana Express',
      'Titas',
      'Transilva',
      'Trust Transport Services (AC)',
      'Trust Transport Services 1',
      'Trust Transport Services 2',
      'Trust Transport Services 3',
      'Turag',
      'VIP 27',
      'Victor Classic',
      'Victor Paribahan',
      'Welcome',
      'Winner'
    ],
    'Mirpur Sony Cinema Hall': ['Himachal', 'Rois'],
    'Khilgaon Khidma Hospital': ['Himachal'],
    'Metro Hall': ['Himachal Suveccha'],
    'Bangladesh Bank': ['Himalay'],
    'Nobinagar Baipayl': ['Itihash'],
    'Kuril Flyover': ['Jabale Noor Paribahan (2)'],
    'Beribadh Tin Rastar Moor': ['Janjabil', 'Prattay'],
    'Rayer Bazar': ['Janjabil', 'Prattay'],
    'Sikder Medical College': ['Janjabil', 'Prattay'],
    'Hazaribag': ['Janjabil', 'Prattay'],
    'Nawabganj': ['Janjabil', 'Prattay'],
    'Kamrangirchar': ['Janjabil', 'Prattay'],
    'Showari Ghat': ['Janjabil', 'Prattay'],
    'Mitford Ghat': ['Janjabil', 'Prattay'],
    'Abdulla': ['Kanak'],
    'Narshinghapur': ['Kironmala Paribahan', 'Power Paribahan'],
    'Sura Bari': ['Kironmala Paribahan', 'Power Paribahan'],
    'Kashimpur': ['Kironmala Paribahan', 'Power Paribahan'],
    'Jarun': ['Kironmala Paribahan', 'Power Paribahan'],
    'Khilgaon Flyover': ['Labbayek', 'MM Lovely', 'Talukdar'],
    'Golapbag Chourasta': ['Labbayek', 'MM Lovely', 'Talukdar'],
    'Kazla': ['Labbayek', 'MM Lovely', 'Talukdar'],
    'Dayaganj': [
      'Malancha',
      'Raja City',
      'Rongdhonu Express',
      'Shahria Enterprise'
    ],
    'Dhupkhola': ['Malancha'],
    'Shanir Akhra': ['Meshkat'],
    'Tolarbag': ['9 No.', 'Mirpur Metro', 'Paristhan'],
    'Manikganj': ['Nilachol', 'Suvajatri'],
    'Paturia': ['Nilachol'],
    'Mirpur 14 Bus Stand': ['Nishorgo'],
    'Dhaka College': ['Nishorgo'],
    'Chalantika Moor': ['Pallabi Local Service'],
    'Mirpur 6': ['Pallabi Local Service'],
    'Joydebpur': ['Provati Banasree'],
    'Sreepur': ['Provati Banasree'],
    'Baromi': ['Provati Banasree'],
    'Dia Bari': ['Raida'],
    'Jurain': ['Raja City', 'Shahria Enterprise', 'Thikana Express'],
    'Fakirapul': ['Rongdhonu Express', 'Shahria Enterprise'],
    'Rajendrapur': ['Shadhin Express', 'Thikana Express'],
    'Tikatuli': ['Shahria Enterprise'],
    'Gandaria': ['Shahria Enterprise'],
    'Shimultola': ['Siam Transport'],
    'Palli Bidyut': ['Siam Transport'],
    'Savar Cantonment': ['Siam Transport'],
    'Rainkhola': ['Somota Paribahan'],
    'Sayedabad Janapath Moor': ['Somoy'],
    'IDB': ['Somoy'],
    'Victoria Park': ['Supravat'],
    'Sanarpar': ['Talukdar'],
    'South Banasree': ['Taranga Plus'],
    'Ring road': ['Tetulia'],
    'Adabor Shyamoli': ['Tetulia'],
    'Shonbari Sreenagar': ['Thikana Express'],
    'Nimtola': ['Thikana Express'],
    'Kuchimura': ['Thikana Express'],
    'Hasnabad': ['Thikana Express'],
    'Nobinagar Chandra': ['Titas'],
    'Press Club Paltan': ['Transilva'],
    'Mirpur 13': ['Trust Transport Services 1', 'Trust Transport Services 2'],
    'Workshop': [
      '4 No. Alike',
      'Trust Transport Services (AC)',
      'Trust Transport Services 2',
      'Trust Transport Services 3'
    ],
    'Saudi Colony': [
      'Trust Transport Services (AC)',
      'Trust Transport Services 2',
      'Trust Transport Services 3'
    ],
    'Mirpur DOHS': [
      'Trust Transport Services (AC)',
      'Trust Transport Services 3'
    ],
    'Garrison (Cantonment)': [
      '4 No. Alike',
      'Trust Transport Services (AC)',
      'Trust Transport Services 3'
    ],
    'Adamjee School': [
      'Trust Transport Services (AC)',
      'Trust Transport Services 3'
    ],
    'Panthapath': ['Winner'],
    'Bot tola': ['Winner'],
    'Signal': ['4 No. Alike'],
    'CMH': ['4 No. Alike'],
    'Adamjee College': ['4 No. Alike'],
  };

  static Set<String>? _stationSetCache;
  static Set<String> get stationSet =>
      _stationSetCache ??= Set<String>.from(stationList);

  // Pre-computed Set<String> per station for O(1) intersection.
  static Map<String, Set<String>>? _stationBusSetsCache;
  static Map<String, Set<String>> get stationBusSets {
    if (_stationBusSetsCache != null) return _stationBusSetsCache!;
    _stationBusSetsCache = {};
    for (final entry in stationMap.entries) {
      _stationBusSetsCache![entry.key] = Set<String>.from(entry.value);
    }
    return _stationBusSetsCache!;
  }

  static List<Bus> getBusesForSegment(String source, String destination) {
    source = source.split(' ').map((w) => w[0].toUpperCase() + w.substring(1)).join(' ');
    destination = destination.split(' ').map((w) => w[0].toUpperCase() + w.substring(1)).join(' ');

    final sourceBusSet = stationBusSets[source] ?? const {};
    final destBusSet = stationBusSets[destination] ?? const {};
    final commonBusNames = sourceBusSet.intersection(destBusSet);

    return commonBusNames
        .where((name) => BusData.buses.containsKey(name))
        .map((name) => BusData.buses[name]!)
        .toList();
  }
}
